# Generated by Django 6.0.1 on 2026-04-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_messagethread_privatemessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainmenu",
            name="menu_order",
            field=models.IntegerField(default=0),
        ),
    ]
