# Generated by Django 6.0.1 on 2026-04-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0004_mainmenu_menu_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="pic_path",
        ),
        migrations.AlterField(
            model_name="book",
            name="picture",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
